### PR TITLE
Removed CI script on push to 'develop'

### PR DESCRIPTION
**Pull request by NSeydoux**
The `status-check.yml` workflow is redundant with the `ci.yml` one, but less complete, so it was removed altogether. The `ci.yml` workflow runs whatever the target branch is, so there is no need to update it following the switch to a 'master' default branch.

### CODE REVIEW

**Comment by acoburn** [comment]
If I'm not mistaken, the `ci.yml` config only runs on `push` events:

https://github.com/inrupt/lit-vocab-term-js/blob/master/.github/workflows/ci.yml#L3

So this will check PRs when the contributor pushes to _this_ repo. But if this is going to be open sourced, you'll need assume that contributors will have their own external fork of the repo. As such, I'd recommend adjusting this a bit so that any `pull_request` triggers a build (or any PR to `master`) and then any `push` to master also triggers a build (since you don't need the duplication).

**Comment by NSeydoux** [comment]
You're right, CI checks must run on PR rather than on push, but I'm not sure I get the end of your comment regarding duplication. 

Do you think it would make sense to run the `build` job of the `ci.yml` script for each PR to `master`, and to run the `release` job on each push, regardless of the branch ? I think it would enable checking PRs from external contributors, while keeping deploying the work done in branches to facilitate testing and collaboration. @Vinnl, would the intended workflow work with this setup ?

**Comment by acoburn** [comment]
By duplication I mean: if you run the checks on _any_ `push` (not just `push` to `master`), then if you `push` to `feature/my-cool-new-thing`, that will trigger a CI build as will the actual PR. I suppose I'm speculating a little here, but this was something that really irked by about appveyor -- you'd push a branch and then make a PR and the CI build ran twice (one at a time, so it took forever). I have a vague memory that with GH Actions, you'd get a duplicate build in that case, too. I could be wrong, but it wouldn't hurt to be explicit.

What I'm suggesting is this:

in `ci.yml`:

```yaml
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```

**Comment by Vinnl** [comment]
@NSeydoux I'm not too familiar with GitHub Actions, so I'm not sure if `push` is only activated for pushes to _this_ repository (though my assumption was that that wasn't the case).

The disadvantage of `pull_request` over `push` is that you have to make a PR to run CI, even though a PR usually indicates that something is ready for review - i.e. _after_ CI has run successfully. This is doubly so the case for the `release` job, which enables you to test it in a production-like environment _before_ pushing it to master. Draft PRs might still enable this flow, but does involve additional manual steps.

So I guess what I would do is: if `push` events also get triggered for pushes to forks, keep it as-is. If not, and if draft PRs also trigger `pull_request` events, then that could be a solution to enable CI builds for forks. (Perhaps it might even be possible to set up a job specifically for PRs from a fork to this repo?)

**Pull request merged**
